import type { ErpData } from "./types";

export const defaultErpData: ErpData = {
  conectaCodes: [
    {
      id: "code-install",
      description: "Instalação FTTA",
      code: "CN-FTTA-001",
      points: 1,
      value: 420,
    },
    {
      id: "code-fusion",
      description: "Fusão de fibra",
      code: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
    },
    {
      id: "code-maintenance",
      description: "Manutenção corretiva",
      code: "CN-MANUT-003",
      points: 0.75,
      value: 260,
    },
  ],
  production: [],
  finance: [
    {
      id: "fin-start",
      date: new Date().toISOString().slice(0, 10),
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 12000,
      paid: true,
    },
    {
      id: "fin-rent",
      date: new Date().toISOString().slice(0, 10),
      description: "Contas fixas",
      type: "Saída",
      category: "Administrativo",
      amount: 3100,
      paid: false,
    },
  ],
  vr: [],
  employees: [
    {
      id: "emp-ana",
      nome: "Ana Cristina",
      cargo: "Coordenadora de Campo",
      equipe: "Operação",
      status: "Ativo",
      dataAdmissao: "2024-02-12",
    },
    {
      id: "emp-bruno",
      nome: "Bruno Martins",
      cargo: "Técnico de Fibra",
      equipe: "Operação",
      status: "Ativo",
      dataAdmissao: "2024-05-03",
    },
    {
      id: "emp-carol",
      nome: "Carolina Nunes",
      cargo: "Analista Financeira",
      equipe: "Financeiro",
      status: "Ativo",
      dataAdmissao: "2023-11-20",
    },
    {
      id: "emp-diego",
      nome: "Diego Almeida",
      cargo: "Consultor Comercial",
      equipe: "Vendas",
      status: "Ativo",
      dataAdmissao: "2025-01-08",
    },
    {
      id: "emp-elaine",
      nome: "Elaine Souza",
      cargo: "Atendimento ao Cliente",
      equipe: "Atendimento",
      status: "Ativo",
      dataAdmissao: "2024-08-15",
    },
    {
      id: "emp-felipe",
      nome: "Felipe Rocha",
      cargo: "Auxiliar Técnico",
      equipe: "Operação",
      status: "Inativo",
      dataAdmissao: "2023-07-01",
    },
  ],
};
