import type { ErpData } from "./types";

export const defaultErpData: ErpData = {
  conectaCodes: [
    {
      id: "code-install",
      description: "InstalaÃ§Ã£o FTTA",
      code: "CN-FTTA-001",
      points: 1,
      value: 420,
    },
    {
      id: "code-fusion",
      description: "FusÃ£o de fibra",
      code: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
    },
    {
      id: "code-maintenance",
      description: "ManutenÃ§Ã£o corretiva",
      code: "CN-MANUT-003",
      points: 0.75,
      value: 260,
    },
  ],
  production: [
    {
      id: "prod-ci-1",
      empresa: "TCI TELECOM",
      date: new Date().toISOString().slice(0, 10),
      sp: "45872",
      cabo: "CTO-12 / FO-08",
      local: "Rua das Palmeiras, 120",
      status: "OK",
      equipe: "LFO-BRUNO J",
      materiais: ["80m fibra", "2 conectores"],
      conectaCodeId: "code-install",
      conectaCode: "CN-FTTA-001",
      points: 1,
      value: 420,
      launchedConecta: true,
      rawMessage: "Mock TCI TELECOM",
    },
    {
      id: "prod-tim-1",
      empresa: "NEW TELECOM",
      date: new Date().toISOString().slice(0, 10),
      sp: "TIM-1042",
      cabo: "BFO-07",
      local: "Central TIM Leste",
      status: "Pendente",
      equipe: "BFO- ELTON",
      materiais: ["1 CTO", "30m cabo"],
      conectaCodeId: "code-maintenance",
      conectaCode: "CN-MANUT-003",
      points: 0.75,
      value: 260,
      launchedConecta: false,
      rawMessage: "Mock NEW TELECOM TIM",
    },
    {
      id: "prod-new-1",
      empresa: "NEW TELECOM",
      date: new Date().toISOString().slice(0, 10),
      sp: "NEW-8821",
      cabo: "CFO-03",
      local: "Base New Telecom",
      status: "OK",
      equipe: "CFO-FABIO",
      materiais: ["60m fibra"],
      conectaCodeId: "code-fusion",
      conectaCode: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
      launchedConecta: true,
      rawMessage: "Mock NEW TELECOM",
    },
    {
      id: "prod-dcf-1",
      empresa: "DCF TELECOM",
      date: new Date().toISOString().slice(0, 10),
      sp: "DCF-2201",
      cabo: "BFO-DCF",
      local: "Operação DCF Vivo",
      status: "OK",
      equipe: "DCF VIVO",
      materiais: ["40m fibra"],
      conectaCodeId: "code-install",
      conectaCode: "CN-FTTA-001",
      points: 1,
      value: 420,
      launchedConecta: true,
      rawMessage: "Mock DCF TELECOM VIVO",
    },
  ],
  finance: [
    {
      id: "fin-start",
      empresa: "TCI TELECOM",
      date: new Date().toISOString().slice(0, 10),
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 12000,
      paid: true,
    },
    {
      id: "fin-rent",
      empresa: "TCI TELECOM",
      date: new Date().toISOString().slice(0, 10),
      description: "Contas fixas",
      type: "Saída",
      category: "Administrativo",
      amount: 3100,
      paid: false,
    },
    {
      id: "fin-dcf-start",
      empresa: "DCF TELECOM",
      date: new Date().toISOString().slice(0, 10),
      description: "Saldo inicial DCF",
      type: "Entrada",
      category: "Caixa",
      amount: 8000,
      paid: true,
    },
    {
      id: "fin-new-start",
      empresa: "NEW TELECOM",
      date: new Date().toISOString().slice(0, 10),
      description: "Saldo inicial New Telecom",
      type: "Entrada",
      category: "Caixa",
      amount: 18000,
      paid: true,
    },
  ],
  vr: [],
  employees: [
    {
      id: "emp-ana",
      empresa: "TCI TELECOM",
      re: "1",
      situacao: "ATIVO",
      nome: "ROBERVAL APARECIDO SILVA - BOLA",
      funcionario: "ROBERVAL APARECIDO SILVA - BOLA",
      cargo: "COORDENADOR",
      seguimento: "REDE",
      equipe: "GESTÃƒO",
      projeto: "GERAL",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 0,00",
      clt: "NÃƒO",
      carro: "",
      placa: "",
      admissao: "0",
      dataAdmissao: "0",
      vencimentoContrato45: "13/02/1900",
      vencimentoContrato90: "29/03/1900",
      eSocial: "",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.298.098-**",
      rg: "***971593",
      nomeMae: "",
      nomePai: "",
      dataNascimento: "",
      enderecoCompleto: "",
      nrs1035: "",
      vencimentoNrs: "",
      possuiNrs: "NÃƒO",
      nrsVencido: "NÃƒO",
      feriasVencidas: "NÃƒO",
      podeTirarFerias: "NÃƒO",
    },
    {
      id: "emp-bruno",
      empresa: "TCI TELECOM",
      re: "4",
      situacao: "ATIVO",
      nome: "CELSO APARECIDO ALDEVINO",
      funcionario: "CELSO APARECIDO ALDEVINO",
      cargo: "SUPERVISOR",
      seguimento: "FTTA",
      equipe: "GESTÃƒO",
      projeto: "VIVO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 3.214,00",
      clt: "SIM",
      carro: "GOL",
      placa: "FWM4E76",
      admissao: "01/07/2025",
      dataAdmissao: "01/07/2025",
      vencimentoContrato45: "14/08/2025",
      vencimentoContrato90: "28/09/2025",
      eSocial: "BJ41",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.364.698-**",
      rg: "***22551",
      nomeMae: "MARINA ALMEIDA ALDEVINO",
      nomePai: "JAIR ALDEVINO",
      dataNascimento: "27/11/1985",
      enderecoCompleto: "SÃƒO PAULO-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃƒO",
      nrsVencido: "NÃƒO",
      feriasVencidas: "NÃƒO",
      podeTirarFerias: "NÃƒO",
    },
    {
      id: "emp-carol",
      empresa: "NEW TELECOM",
      re: "8",
      situacao: "ATIVO",
      nome: "ELTON DOS SANTOS GIRÃƒO",
      funcionario: "ELTON DOS SANTOS GIRÃƒO",
      cargo: "OFICIAL DE REDE 2",
      seguimento: "BFO",
      equipe: "BFO- ELTON",
      projeto: "VIVO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.255,48",
      clt: "SIM",
      carro: "GOL",
      placa: "FYD4C26",
      admissao: "24/06/2024",
      dataAdmissao: "24/06/2024",
      vencimentoContrato45: "13/02/1900",
      vencimentoContrato90: "29/03/1900",
      eSocial: "BJ21",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.841.853-**",
      rg: "***112378",
      nomeMae: "FIDELES CONRADO GIRAO NETO",
      nomePai: "ISAIAS DOS SANTOS GIRAO",
      dataNascimento: "04/09/1996",
      enderecoCompleto: "TABOÃƒO DA SERRA-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃƒO",
      nrsVencido: "NÃƒO",
      feriasVencidas: "NÃƒO",
      podeTirarFerias: "NÃƒO",
    },
    {
      id: "emp-diego",
      empresa: "NEW TELECOM",
      re: "9",
      situacao: "ATIVO",
      nome: "FABIO RODRIGUES DA SILVA",
      funcionario: "FABIO RODRIGUES DA SILVA",
      cargo: "CABISTA DE FIBRA",
      seguimento: "CFO - B2B",
      equipe: "CFO-FABIO",
      projeto: "CLARO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.710,77",
      clt: "SIM",
      carro: "",
      placa: "",
      admissao: "06/05/2024",
      dataAdmissao: "06/05/2024",
      vencimentoContrato45: "23/06/2024",
      vencimentoContrato90: "07/08/2024",
      eSocial: "BJ19",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.321.948-**",
      rg: "***930364",
      nomeMae: "REGINA CELIA RODRIGUES DA SILVA",
      nomePai: "JORGE RODRIGUES DA SILVA",
      dataNascimento: "31/07/1995",
      enderecoCompleto: "SÃƒO PAULO-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃƒO",
      nrsVencido: "NÃƒO",
      feriasVencidas: "NÃƒO",
      podeTirarFerias: "SIM",
    },
    {
      id: "emp-elaine",
      empresa: "NEW TELECOM",
      re: "10",
      situacao: "INATIVO",
      nome: "BRUNO LISBOA DE LIMA OLIVEIRA",
      funcionario: "BRUNO LISBOA DE LIMA OLIVEIRA",
      cargo: "CABISTA DE FIBRA",
      seguimento: "CFO - B2B",
      equipe: "CFO-BRUNO L",
      projeto: "CLARO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.673,74",
      clt: "SIM",
      carro: "KIWID",
      placa: "SUJ1H75",
      admissao: "0",
      dataAdmissao: "0",
      vencimentoContrato45: "13/02/1900",
      vencimentoContrato90: "29/03/1900",
      eSocial: "BJ31",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.654.458-**",
      rg: "***090308",
      nomeMae: "",
      nomePai: "",
      dataNascimento: "",
      enderecoCompleto: "",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃƒO",
      nrsVencido: "NÃƒO",
      feriasVencidas: "NÃƒO",
      podeTirarFerias: "NÃƒO",
    },
    {
      id: "emp-felipe",
      empresa: "NEW TELECOM",
      re: "14",
      situacao: "ATIVO",
      nome: "BRUNO JOSUE DOS SANTOS RIBEIRO",
      funcionario: "BRUNO JOSUE DOS SANTOS RIBEIRO",
      cargo: "OFICIAL DE REDE",
      seguimento: "FTTA",
      equipe: "LFO-BRUNO J",
      projeto: "CLARO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.009,11",
      clt: "SIM",
      carro: "KIWID",
      placa: "SWT54D54",
      admissao: "24/06/2025",
      dataAdmissao: "24/06/2025",
      vencimentoContrato45: "07/08/2025",
      vencimentoContrato90: "21/09/2025",
      eSocial: "BJ40",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.234.108-**",
      rg: "***423846",
      nomeMae: "MARIA SEVERINA DOS SANTOS",
      nomePai: "MARIVALDO FAGUNDES RIBEIRO",
      dataNascimento: "10/08/1996",
      enderecoCompleto: "SÃƒO PAULO-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃƒO",
      nrsVencido: "NÃƒO",
      feriasVencidas: "NÃƒO",
      podeTirarFerias: "NÃƒO",
    },
    {
      id: "emp-dcf-1",
      empresa: "DCF TELECOM",
      re: "DCF-1",
      situacao: "ATIVO",
      nome: "Equipe DCF Vivo",
      funcionario: "Equipe DCF Vivo",
      cargo: "OFICIAL DE REDE",
      seguimento: "BFO",
      equipe: "DCF VIVO",
      projeto: "VIVO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.255,48",
      clt: "SIM",
      carro: "",
      placa: "",
      admissao: "",
      dataAdmissao: "",
      vencimentoContrato45: "",
      vencimentoContrato90: "",
      eSocial: "",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "",
      rg: "",
      nomeMae: "",
      nomePai: "",
      dataNascimento: "",
      enderecoCompleto: "",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "SIM",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
  ],
};



