import type { ErpData } from "./types";

export const defaultErpData: ErpData = {
  conectaCodes: [
    {
      id: "code-install",
      description: "Instalação FTTA",
      code: "CN-FTTA-001",
      points: 1,
      value: 420,
    },
    {
      id: "code-fusion",
      description: "Fusão de fibra",
      code: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
    },
    {
      id: "code-maintenance",
      description: "Manutenção corretiva",
      code: "CN-MANUT-003",
      points: 0.75,
      value: 260,
    },
  ],
  production: [],
  finance: [
    {
      id: "fin-start",
      date: new Date().toISOString().slice(0, 10),
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 12000,
      paid: true,
    },
    {
      id: "fin-rent",
      date: new Date().toISOString().slice(0, 10),
      description: "Contas fixas",
      type: "Saída",
      category: "Administrativo",
      amount: 3100,
      paid: false,
    },
  ],
  vr: [],
  employees: [
    {
      id: "emp-ana",
      re: "1",
      situacao: "ATIVO",
      nome: "ROBERVAL APARECIDO SILVA - BOLA",
      funcionario: "ROBERVAL APARECIDO SILVA - BOLA",
      cargo: "COORDENADOR",
      seguimento: "REDE",
      equipe: "GESTÃO",
      projeto: "GERAL",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 0,00",
      clt: "NÃO",
      carro: "",
      placa: "",
      admissao: "0",
      dataAdmissao: "0",
      vencimentoContrato45: "13/02/1900",
      vencimentoContrato90: "29/03/1900",
      eSocial: "",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.298.098-**",
      rg: "***971593",
      nomeMae: "",
      nomePai: "",
      dataNascimento: "",
      enderecoCompleto: "",
      nrs1035: "",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
    {
      id: "emp-bruno",
      re: "4",
      situacao: "ATIVO",
      nome: "CELSO APARECIDO ALDEVINO",
      funcionario: "CELSO APARECIDO ALDEVINO",
      cargo: "SUPERVISOR",
      seguimento: "FTTA",
      equipe: "GESTÃO",
      projeto: "VIVO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 3.214,00",
      clt: "SIM",
      carro: "GOL",
      placa: "FWM4E76",
      admissao: "01/07/2025",
      dataAdmissao: "01/07/2025",
      vencimentoContrato45: "14/08/2025",
      vencimentoContrato90: "28/09/2025",
      eSocial: "BJ41",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.364.698-**",
      rg: "***22551",
      nomeMae: "MARINA ALMEIDA ALDEVINO",
      nomePai: "JAIR ALDEVINO",
      dataNascimento: "27/11/1985",
      enderecoCompleto: "SÃO PAULO-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
    {
      id: "emp-carol",
      re: "8",
      situacao: "ATIVO",
      nome: "ELTON DOS SANTOS GIRÃO",
      funcionario: "ELTON DOS SANTOS GIRÃO",
      cargo: "OFICIAL DE REDE 2",
      seguimento: "BFO",
      equipe: "BFO- ELTON",
      projeto: "VIVO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.255,48",
      clt: "SIM",
      carro: "GOL",
      placa: "FYD4C26",
      admissao: "24/06/2024",
      dataAdmissao: "24/06/2024",
      vencimentoContrato45: "13/02/1900",
      vencimentoContrato90: "29/03/1900",
      eSocial: "BJ21",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.841.853-**",
      rg: "***112378",
      nomeMae: "FIDELES CONRADO GIRAO NETO",
      nomePai: "ISAIAS DOS SANTOS GIRAO",
      dataNascimento: "04/09/1996",
      enderecoCompleto: "TABOÃO DA SERRA-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
    {
      id: "emp-diego",
      re: "9",
      situacao: "ATIVO",
      nome: "FABIO RODRIGUES DA SILVA",
      funcionario: "FABIO RODRIGUES DA SILVA",
      cargo: "CABISTA DE FIBRA",
      seguimento: "CFO - B2B",
      equipe: "CFO-FABIO",
      projeto: "CLARO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.710,77",
      clt: "SIM",
      carro: "",
      placa: "",
      admissao: "06/05/2024",
      dataAdmissao: "06/05/2024",
      vencimentoContrato45: "23/06/2024",
      vencimentoContrato90: "07/08/2024",
      eSocial: "BJ19",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.321.948-**",
      rg: "***930364",
      nomeMae: "REGINA CELIA RODRIGUES DA SILVA",
      nomePai: "JORGE RODRIGUES DA SILVA",
      dataNascimento: "31/07/1995",
      enderecoCompleto: "SÃO PAULO-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "SIM",
    },
    {
      id: "emp-elaine",
      re: "10",
      situacao: "INATIVO",
      nome: "BRUNO LISBOA DE LIMA OLIVEIRA",
      funcionario: "BRUNO LISBOA DE LIMA OLIVEIRA",
      cargo: "CABISTA DE FIBRA",
      seguimento: "CFO - B2B",
      equipe: "CFO-BRUNO L",
      projeto: "CLARO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.673,74",
      clt: "SIM",
      carro: "KIWID",
      placa: "SUJ1H75",
      admissao: "0",
      dataAdmissao: "0",
      vencimentoContrato45: "13/02/1900",
      vencimentoContrato90: "29/03/1900",
      eSocial: "BJ31",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.654.458-**",
      rg: "***090308",
      nomeMae: "",
      nomePai: "",
      dataNascimento: "",
      enderecoCompleto: "",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
    {
      id: "emp-felipe",
      re: "14",
      situacao: "ATIVO",
      nome: "BRUNO JOSUE DOS SANTOS RIBEIRO",
      funcionario: "BRUNO JOSUE DOS SANTOS RIBEIRO",
      cargo: "OFICIAL DE REDE",
      seguimento: "FTTA",
      equipe: "LFO-BRUNO J",
      projeto: "CLARO",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 2.009,11",
      clt: "SIM",
      carro: "KIWID",
      placa: "SWT54D54",
      admissao: "24/06/2025",
      dataAdmissao: "24/06/2025",
      vencimentoContrato45: "07/08/2025",
      vencimentoContrato90: "21/09/2025",
      eSocial: "BJ40",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.234.108-**",
      rg: "***423846",
      nomeMae: "MARIA SEVERINA DOS SANTOS",
      nomePai: "MARIVALDO FAGUNDES RIBEIRO",
      dataNascimento: "10/08/1996",
      enderecoCompleto: "SÃO PAULO-SP",
      nrs1035: "SIM",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
  ],
};
